version: "3.8"

services:
  printer:
    build: .
    container_name: hp_printer_setup
    privileged: true
    restart: always
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
    environment:
      - DEBIAN_FRONTEND=noninteractive
